---
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - ${postgres_port}
    volumes:
      - rest_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_pwd}
      POSTGRES_DB: ${postgres_db}
volumes:
  rest_db_volume:
    driver: local
